
permalink:           pretty

# Setup
title:               CDBlog
tagline:             'iOS Team @ Codoon'
description:         ''
url:                 http://ioscodoon.github.io/CDBlog
baseurl:             ''

plugins:             [jekyll-paginate]
paginate:            5
paginate_path:       "page:num"

# About/contact
author:
  name:              iOSCodoon
  url:               http://ioscodoon.github.io/CDBlog
  email:             ios@codoon.com

# Custom vars
version:             1.0.0
